"""okk.

Revision ID: 4a141fa79ff9
Revises: bacb2c4d2bb0
Create Date: 2024-04-25 21:46:47.805922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a141fa79ff9'
down_revision = 'bacb2c4d2bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra__info__profile', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint('extra__info__profile_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profiles', ['prof_id'], ['id'])

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('profiles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profiles_ibfk_1', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('extra__info__profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('extra__info__profile_ibfk_1', 'profiles', ['prof_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
